import BtreeMap

BtreeMap.AddDuo(1,"hello")
BtreeMap.AddDuo(2,"world")
BtreeMap.AddDuo(4, "Ehe")
BtreeMap.AddDuo(3, "No hehe")
BtreeMap.PrintTree(); print()
BtreeMap.AddDuo(3, "hehe")
BtreeMap.AddDuo(4, "yes")
BtreeMap.PrintTree()
BtreeMap.GetValue(3)
BtreeMap.DoVoidTree()
BtreeMap.GetValue(1)
BtreeMap.GetValue(5)
BtreeMap.PrintTree()